image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: metrics.local

envFrom:
  -secretRef:
     PASSWORD: password
